package ${project.base.package}.service.${class.package.name}.model;

/**
 * Created by ${user.first_name} ${user.last_name}.
 * Date: ${class.created.date}
 * Time: ${class.created.time} PM
 */
public class ${class.name} {

    //region Properties
    //endregion

    //region Constructors
    public ${class.name}() {
        // Default constructor
    }
    //endregion

    //region Equals, HashCode and ToString
    //endregion

    //region Properties getters and setters
    //endregion

}
